version: "3"
services:
  kafka:
    image: confluentinc/cp-kafka:5.0.0-2
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_BROKER_ID: 1
    restart: on-failure
  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.0-2
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:1.6
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "14267"
      - "14268:14268"
      - "14269"
      - "16686:16686"
      - "16687"
      - "9411:9411"
    restart: on-failure

# Tip: to remove messages from Redis
#   - find its container ID from `docker ps`
#   - start redis-cli as below
#   - remove the message by uuid
#
# $ docker exec -it d8414a656714 redis-cli
# 127.0.0.1:6379> zrange lobby 0 -1
# 1) "2088417b-f09c-4613-8cb3-f91a5c4c10bf"
# 2) "5464d168-7d72-419f-96dc-745905721313"
# 3) "0f9594a6-fa08-4ad4-97f6-4781541b919d"
# 4) "564d1f2a-68f8-49b2-97de-f5953f1fdbb9"
# 127.0.0.1:6379> zrem lobby 564d1f2a-68f8-49b2-97de-f5953f1fdbb9
# (integer) 1
# 127.0.0.1:6379> zrange lobby 0 -1
# 1) "2088417b-f09c-4613-8cb3-f91a5c4c10bf"
# 2) "5464d168-7d72-419f-96dc-745905721313"
# 3) "0f9594a6-fa08-4ad4-97f6-4781541b919d"
